-- Dr. Ahmad Ali website: moderated reader reviews
-- Run this once in the Supabase SQL Editor.

create table if not exists public.book_reviews (
  id bigint generated by default as identity primary key,
  book_id text not null,
  book_title text,
  name text not null check (char_length(name) between 1 and 100),
  email text,
  review text not null check (char_length(review) between 2 and 3000),
  created_at timestamptz not null default now(),
  approved boolean not null default false
);

create index if not exists book_reviews_book_date_idx
  on public.book_reviews (book_id, created_at desc);

alter table public.book_reviews enable row level security;

-- The browser gets NO direct table permissions. Email therefore cannot be queried publicly.
revoke all on table public.book_reviews from anon, authenticated;

create or replace function public.submit_book_review(
  p_book_id text,
  p_book_title text,
  p_name text,
  p_email text,
  p_review text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id bigint;
  clean_name text := btrim(coalesce(p_name,''));
  clean_email text := nullif(btrim(coalesce(p_email,'')), '');
  clean_review text := btrim(coalesce(p_review,''));
begin
  if char_length(clean_name) < 1 or char_length(clean_name) > 100 then
    raise exception 'Invalid name';
  end if;
  if clean_email is not null and (char_length(clean_email) > 200 or clean_email !~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$') then
    raise exception 'Invalid email';
  end if;
  if char_length(clean_review) < 2 or char_length(clean_review) > 3000 then
    raise exception 'Invalid review';
  end if;
  if char_length(coalesce(p_book_id,'')) < 1 or char_length(p_book_id) > 160 then
    raise exception 'Invalid book';
  end if;

  insert into public.book_reviews(book_id,book_title,name,email,review,approved)
  values (p_book_id,left(coalesce(p_book_title,''),300),clean_name,clean_email,clean_review,false)
  returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.get_book_reviews(p_book_id text)
returns table(id bigint,name text,review text,created_at timestamptz)
language sql
security definer
set search_path = public
stable
as $$
  select r.id,r.name,r.review,r.created_at
  from public.book_reviews r
  where r.book_id=p_book_id and r.approved=true
  order by r.created_at desc,r.id desc;
$$;

revoke all on function public.submit_book_review(text,text,text,text,text) from public;
revoke all on function public.get_book_reviews(text) from public;
grant usage on schema public to anon, authenticated;
grant execute on function public.submit_book_review(text,text,text,text,text) to anon, authenticated;
grant execute on function public.get_book_reviews(text) to anon, authenticated;
