(()=>{
const cfg=window.AHMAD_ALI_REVIEW_CONFIG||{}, supabaseUrl=(cfg.supabaseUrl||'').replace(/\/$/,''), key=cfg.publishableKey||'';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let session=JSON.parse(sessionStorage.getItem('aaAdminSession')||'null'), type='book', editing=null, locale='bn';
const data=()=>({book:window.ahmadAliBookDetails||[],post:window.windowOfTimePosts||[],article:window.ahmadAliSelectedArticles||[],publication:window.ahmadAliPublications||[],update:window.ahmadAliUpdates||[]})[type]||[];
const labels={book:['Books','বই'],post:['Posts','পোস্ট'],article:['Selected Articles','নির্বাচিত প্রবন্ধ'],publication:['Publications','প্রকাশনা'],update:['Updates','আপডেট']};
function msg(el,text,ok=false){el.textContent=text;el.className='msg '+(ok?'ok':'error')}
async function authFetch(path,opt={}){opt.headers={...(opt.headers||{}),apikey:key,Authorization:`Bearer ${session?.access_token||''}`};let r=await fetch(supabaseUrl+path,opt);if(r.status===401&&session?.refresh_token){const rr=await fetch(`${supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});if(rr.ok){session=await rr.json();sessionStorage.setItem('aaAdminSession',JSON.stringify(session));opt.headers.Authorization=`Bearer ${session.access_token}`;r=await fetch(supabaseUrl+path,opt)}}return r}
async function call(payload){const r=await authFetch('/functions/v1/site-admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||`Request failed (${r.status})`);return j}
async function login(email,password){if(!supabaseUrl||!key)throw new Error('Supabase URL/publishable key is missing in reviews-config.js.');const r=await fetch(`${supabaseUrl}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const j=await r.json();if(!r.ok)throw new Error(j.msg||j.error_description||'Login failed.');session=j;sessionStorage.setItem('aaAdminSession',JSON.stringify(j));return await call({action:'whoami'})}
function logout(){session=null;sessionStorage.removeItem('aaAdminSession');$('#appPanel').hidden=true;$('#loginPanel').hidden=false;$('#logoutBtn').hidden=true}
function idFor(t){const d=new Date().toISOString().slice(0,10),rnd=Math.random().toString(36).slice(2,8);return t==='post'?`${d}-post-${rnd}`:t==='article'?`${d}-article-${rnd}`:t==='update'?`${d}-update-${rnd}`:t==='publication'?`publication-${Date.now().toString().slice(-9)}`:`book-${Date.now().toString().slice(-9)}`}
function val(n){return $('#contentForm').elements[n]?.value?.trim?.()??''} function check(n){return !!$('#contentForm').elements[n]?.checked}
function field(n,l,v='',t='text',req=false){return `<label>${l}${req?' *':''}<input name="${n}" type="${t}" value="${esc(v)}" ${req?'required':''}></label>`}
function area(n,l,v='',cls=''){return `<label>${l}<textarea name="${n}" class="${cls}">${esc(v)}</textarea></label>`}
function select(n,l,opts,v=''){return `<label>${l}<select name="${n}">${opts.map(([x,y])=>`<option value="${esc(x)}" ${String(x)===String(v)?'selected':''}>${esc(y)}</option>`).join('')}</select></label>`}
function topics(v){return select('topic_slug','Topic / বিষয়',Object.entries(window.ahmadAliTopicTaxonomy||{}).map(([s,o])=>[s,`${o.bn} — ${o.en}`]),v)}
function commonId(item){const id=item?.id||idFor(type);return `<fieldset class="fieldset"><legend>Record</legend><label>ID *<input name="id" type="text" value="${esc(id)}" required ${item?.id?'readonly':''}></label><p class="small">ID is the permanent file identifier. It is locked after publishing.</p></fieldset>`}
function bookForm(b={}){const m=b.meta||{},e=b.en||{},n=b.bn||{},media=b.media||{},pub=(b.links||[]).find(x=>/^publisher/i.test(x.label||''));return commonId(b)+`<fieldset class="fieldset"><legend>Book status</legend><div class="three">${select('status','Status',[['published','Published'],['forthcoming','Forthcoming']],b.status||'published')}${field('category','Category',b.category||'')}${select('series','Series',[['','None'],['bidat','Bid‘ah'],['usulul-iman','Usul al-Iman'],['zubdatul-bayan','Zubdat al-Bayan']],b.series||'')}</div></fieldset><fieldset class="fieldset"><legend>বাংলা</legend>${field('bn_title','শিরোনাম',n.title||'','text',true)}${field('bn_subtitle','উপশিরোনাম',n.subtitle||'')}${area('bn_summary','বই পরিচিতি',n.summary||'')}</fieldset><fieldset class="fieldset"><legend>English</legend>${field('en_title','Title',e.title||'','text',true)}${field('en_original','Original Bengali title',e.originalTitle||n.title||'')}${field('en_subtitle','Subtitle',e.subtitle||'')}${area('en_summary','Description',e.summary||'')}</fieldset><fieldset class="fieldset"><legend>Publication details</legend><div class="two">${field('publisher','Publisher',m.publisher||'')}${field('publisherBn','প্রকাশক',m.publisherBn||'')}${field('publicationYear','Publication year',m.publicationYear||'')}${field('isbn','ISBN',m.isbn||'')}${field('edition','Edition',m.edition||'')}${field('editionBn','সংস্করণ',m.editionBn||'')}${field('pages','Pages',m.pages||'')}${field('binding','Binding',m.binding||'')}${field('bindingBn','বাঁধাই',m.bindingBn||'')}${field('country','Country',m.country||'')}${field('countryBn','দেশ',m.countryBn||'')}${field('language','Language',m.language||'')}${field('languageBn','ভাষা',m.languageBn||'')}</div></fieldset><fieldset class="fieldset"><legend>Links & media</legend>${field('rokomariUrl','Rokomari URL',b.rokomariUrl||'','url')}${field('publisherUrl','Publisher URL',pub?.url||'','url')}${field('preview','Preview URL',media.preview||'','url')}${field('pdfUrl','Existing PDF URL/path',media.pdf||'')}${field('audioUrl','Audiobook URL/path',media.audio?.[0]?.url||'')}${field('audioTitle','Audiobook title',media.audio?.[0]?.title||'')}<div class="two">${field('coverFile','Upload/replace cover','','file')}${field('pdfFile','Upload small PDF (max 6 MB)','','file')}</div><p class="small">Large PDFs should be hosted externally and pasted into the PDF URL field.</p></fieldset>`}
function postForm(p={}){return commonId(p)+`<fieldset class="fieldset"><legend>Post</legend><div class="two">${field('date','Date',p.date||new Date().toISOString().slice(0,10),'date',true)}${topics(p.topic_slug||'islamic-thought-philosophy')}</div><div class="three">${select('sourceType','Source type',[['facebook','Facebook'],['newspaper','Newspaper'],['magazine','Magazine'],['blog','Blog'],['website','Website'],['other','Other']],p.source?.type||'facebook')}${field('sourceLabel','Source label',p.source?.label||'Facebook')}${field('sourceUrl','Original source URL',p.source?.url||'','url')}</div></fieldset><fieldset class="fieldset"><legend>বাংলা</legend>${field('bn_title','শিরোনাম',p.bn?.title||'','text',true)}${area('bn_body','সম্পূর্ণ লেখা',p.bn?.body||'','body-text')}</fieldset><fieldset class="fieldset"><legend>English</legend>${field('en_title','Title',p.en?.title||'','text',true)}${area('en_body','Full text',p.en?.body||'','body-text')}</fieldset>`}
function articleForm(a={}){return commonId(a)+`<fieldset class="fieldset"><legend>Article</legend><div class="two">${field('date','Date',a.date||new Date().toISOString().slice(0,10),'date',true)}${topics(a.topic_slug||'islamic-thought-philosophy')}</div>${field('sourceUrl','Source URL',a.source?.url||'','url')}</fieldset><fieldset class="fieldset"><legend>বাংলা</legend>${field('bn_title','শিরোনাম',a.bn?.title||'','text',true)}${field('bn_dateLabel','তারিখ প্রদর্শন',a.bn?.dateLabel||'')}${field('sourceBn','উৎস',a.source?.labelBn||'')}${area('bn_excerpt','সংক্ষিপ্ত পরিচিতি',a.bn?.excerpt||'')}${area('bn_body','সম্পূর্ণ প্রবন্ধ',a.bn?.body||'','body-text')}</fieldset><fieldset class="fieldset"><legend>English</legend>${field('en_title','Title',a.en?.title||'','text',true)}${field('en_dateLabel','Display date',a.en?.dateLabel||'')}${field('sourceEn','Source',a.source?.labelEn||'')}${area('en_excerpt','Excerpt',a.en?.excerpt||'')}${area('en_body','Full article',a.en?.body||'','body-text')}</fieldset>`}
function publicationForm(p={}){return commonId(p)+`<fieldset class="fieldset"><legend>Publication type</legend><div class="three">${select('pubType','Type',[['research','Research article/paper'],['arabic','Arabic publication'],['edited','Edited work'],['translation','Translation']],p.type||'research')}${field('order','Display order',p.order||999,'number')}${field('language','Language',p.language||'Bengali')}</div><div class="two">${field('dateLabelEn','Date label (EN)',p.dateLabelEn||'')}${field('dateLabelBn','তারিখ (বাংলা)',p.dateLabelBn||'')}</div></fieldset><fieldset class="fieldset"><legend>Titles</legend>${field('titleEn','English title',p.titleEn||'')}${field('titleBn','বাংলা শিরোনাম',p.titleBn||'')}${field('titleAr','العنوان العربي',p.titleAr||'')}${field('originalTitleBn','Original Bengali title shown under English title',p.originalTitleBn||'')}</fieldset><fieldset class="fieldset"><legend>Bibliographic details</legend><div class="two">${field('sourceEn','Journal/source (EN)',p.sourceEn||'')}${field('sourceBn','জার্নাল/উৎস',p.sourceBn||'')}${field('sourceAr','المصدر',p.sourceAr||'')}${field('volume','Volume',p.volume||'')}${field('issue','Issue',p.issue||'')}${field('pages','Pages',p.pages||'')}${field('publisherEn','Publisher (EN)',p.publisherEn||'')}${field('publisherBn','প্রকাশক',p.publisherBn||'')}${field('issueDateEn','Original issue date (EN)',p.issueDateEn||'')}${field('issueDateBn','মূল সংখ্যা প্রকাশকাল',p.issueDateBn||'')}${field('onlineDateEn','OJS/online date (EN)',p.onlineDateEn||'')}${field('onlineDateBn','OJS/অনলাইন প্রকাশকাল',p.onlineDateBn||'')}</div>${area('detailsEn','Additional citation/details (EN)',p.detailsEn||'')}${area('detailsBn','অতিরিক্ত বিবরণ (বাংলা)',p.detailsBn||'')}${area('notesEn','Notes (EN)',p.notesEn||'')}${area('notesBn','নোট (বাংলা)',p.notesBn||'')}</fieldset><fieldset class="fieldset"><legend>Links</legend>${field('articleUrl','Article URL',p.articleUrl||'','url')}${field('doi','DOI URL',p.doi||'','url')}${field('pdfUrl','PDF URL/path',p.pdfUrl||'')}${field('otherUrl','Other URL',p.otherUrl||'','url')}${field('pubPdfFile','Upload small PDF (max 6 MB)','','file')}</fieldset>`}
function updateForm(u={}){return commonId(u)+`<fieldset class="fieldset"><legend>Update</legend><div class="two">${field('date','Date',u.date||new Date().toISOString().slice(0,10),'date',true)}${field('href','Link / page',u.href||'')}</div></fieldset><fieldset class="fieldset"><legend>বাংলা</legend>${field('bn_title','শিরোনাম',u.bn?.title||'','text',true)}${area('bn_summary','বিবরণ',u.bn?.summary||'')}</fieldset><fieldset class="fieldset"><legend>English</legend>${field('en_title','Title',u.en?.title||'','text',true)}${area('en_summary','Summary',u.en?.summary||'')}</fieldset>`}
function renderForm(item){editing=item||null;$('#editorPanel').hidden=false;$('#editorTitle').textContent=(item?'Edit ':'Add ')+(labels[type]?.[0]||type);$('#contentForm').innerHTML=({book:bookForm,post:postForm,article:articleForm,publication:publicationForm,update:updateForm}[type])(item||{})+`<div class="form-actions"><button type="button" id="cancelBtn">Cancel</button><button class="primary" type="submit">Save & publish</button></div>`;$('#cancelBtn').onclick=()=>$('#editorPanel').hidden=true}
function displayTitle(x){if(type==='book')return x.bn?.title||x.en?.title||x.id;if(type==='post'||type==='article')return x.bn?.title||x.en?.title||x.id;if(type==='publication')return x.titleBn||x.titleEn||x.titleAr||x.id;if(type==='update')return x.bn?.title||x.en?.title||x.id;return x.id}
function renderList(){const q=$('#listSearch').value.toLowerCase();const list=data().filter(x=>displayTitle(x).toLowerCase().includes(q)||String(x.id||'').includes(q));$('#sectionTitle').textContent=`${labels[type][0]} / ${labels[type][1]}`;document.querySelectorAll('#typeNav button').forEach(b=>b.classList.toggle('active',b.dataset.type===type));$('#contentList').innerHTML=list.map(x=>`<div class="content-row"><div><strong>${esc(displayTitle(x))}</strong><small>${esc(x.id||'')} ${x.date?' · '+esc(x.date):''}</small></div><div class="row-actions"><button data-edit="${esc(x.id)}">Edit</button><button class="danger" data-del="${esc(x.id)}">Delete</button></div></div>`).join('')||'<p>No items found.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>renderForm(data().find(x=>x.id===b.dataset.edit)));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>removeItem(b.dataset.del))}
async function fileBase64(file){if(!file)return null;if(file.size>6*1024*1024)throw new Error('File is larger than 6 MB. Use an external URL for large PDFs.');return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(file)})}
async function upload(file,id,kind,contentType='book'){if(!file)return '';const ext=(file.name.split('.').pop()||'bin').toLowerCase();const base64=await fileBase64(file);const j=await call({action:'upload',contentType,id,kind,ext,base64});return j.path}
function makeData(){const id=val('id');if(type==='book'){const old=editing||{},coverFile=$('#contentForm').elements.coverFile.files[0],pdfFile=$('#contentForm').elements.pdfFile.files[0];return {id,uploads:{coverFile,pdfFile},data:{id,order:Number(old.order||999),status:val('status'),rokomariId:old.rokomariId||'',category:val('category'),series:val('series')||null,rokomariUrl:val('rokomariUrl'),links:val('publisherUrl')?[{label:'Publisher',labelBn:'প্রকাশক',url:val('publisherUrl')}]:[],en:{title:val('en_title'),originalTitle:val('en_original'),subtitle:val('en_subtitle'),summary:val('en_summary')},bn:{title:val('bn_title'),subtitle:val('bn_subtitle'),summary:val('bn_summary')},meta:{publisher:val('publisher'),publisherBn:val('publisherBn'),publicationYear:val('publicationYear'),isbn:val('isbn'),edition:val('edition'),editionBn:val('editionBn'),pages:val('pages'),binding:val('binding'),bindingBn:val('bindingBn'),country:val('country'),countryBn:val('countryBn'),language:val('language'),languageBn:val('languageBn')},media:{cover:old.media?.cover||null,preview:val('preview')||null,pdf:val('pdfUrl')||old.media?.pdf||null,audio:val('audioUrl')?[{title:val('audioTitle')||'Audiobook',titleBn:val('audioTitle')||'অডিওবুক',url:val('audioUrl')}]:[]}}}}
if(type==='post')return{id,data:{id,date:val('date'),topic_slug:val('topic_slug'),source:{type:val('sourceType'),label:val('sourceLabel'),url:val('sourceUrl')},bn:{title:val('bn_title'),body:val('bn_body')},en:{title:val('en_title'),body:val('en_body')}}};
if(type==='article')return{id,data:{id,date:val('date'),topic_slug:val('topic_slug'),source:{labelBn:val('sourceBn'),labelEn:val('sourceEn'),url:val('sourceUrl')},bn:{title:val('bn_title'),dateLabel:val('bn_dateLabel'),excerpt:val('bn_excerpt'),body:val('bn_body')},en:{title:val('en_title'),dateLabel:val('en_dateLabel'),excerpt:val('en_excerpt'),body:val('en_body')}}};
if(type==='publication'){const d={};['pubType','order','language','dateLabelEn','dateLabelBn','titleEn','titleBn','titleAr','originalTitleBn','sourceEn','sourceBn','sourceAr','volume','issue','pages','publisherEn','publisherBn','issueDateEn','issueDateBn','onlineDateEn','onlineDateBn','detailsEn','detailsBn','notesEn','notesBn','articleUrl','doi','pdfUrl','otherUrl'].forEach(k=>d[k]=val(k));d.type=d.pubType;delete d.pubType;d.order=Number(d.order||999);d.id=id;return{id,uploads:{pubPdfFile:$('#contentForm').elements.pubPdfFile.files[0]},data:d};}
return{id,data:{id,date:val('date'),href:val('href'),en:{title:val('en_title'),summary:val('en_summary')},bn:{title:val('bn_title'),summary:val('bn_summary')}}}}
async function save(e){e.preventDefault();const sm=$('#saveMsg');sm.textContent='Saving…';sm.className='msg';try{const pack=makeData();if(type==='book'){if(pack.uploads.coverFile)pack.data.media.cover=await upload(pack.uploads.coverFile,pack.id,'cover','book');if(pack.uploads.pdfFile)pack.data.media.pdf=await upload(pack.uploads.pdfFile,pack.id,'pdf','book')}if(type==='publication'&&pack.uploads.pubPdfFile)pack.data.pdfUrl=await upload(pack.uploads.pubPdfFile,pack.id,'pdf','publication');await call({action:'save',contentType:type,id:pack.id,data:pack.data});const arr=data();const i=arr.findIndex(x=>x.id===pack.id);if(i>=0)arr[i]=pack.data;else arr.unshift(pack.data);renderList();msg(sm,'Published to GitHub. The public index normally rebuilds within about a minute.',true)}catch(err){msg(sm,err.message)}}
async function removeItem(id){if(!confirm(`Delete ${displayTitle(data().find(x=>x.id===id)||{id})}?`))return;try{await call({action:'delete',contentType:type,id});const arr=data();const i=arr.findIndex(x=>x.id===id);if(i>=0)arr.splice(i,1);renderList();alert('Deleted from GitHub. The public index will rebuild shortly.');}catch(e){alert(e.message)}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const r=await login(e.target.email.value,e.target.password.value);$('#loginPanel').hidden=true;$('#appPanel').hidden=false;$('#logoutBtn').hidden=false;$('#adminIdentity').textContent=r.email;renderList()}catch(err){msg($('#loginMsg'),err.message)}};$('#logoutBtn').onclick=logout;$('#contentForm').onsubmit=save;$('#addBtn').onclick=()=>renderForm(null);$('#closeEditor').onclick=()=>$('#editorPanel').hidden=true;$('#listSearch').oninput=renderList;document.querySelectorAll('#typeNav button').forEach(b=>b.onclick=()=>{type=b.dataset.type;$('#editorPanel').hidden=true;renderList()});$('#langBtn').onclick=()=>{locale=locale==='bn'?'en':'bn';document.documentElement.lang=locale};
(async()=>{if(session){try{const r=await call({action:'whoami'});$('#loginPanel').hidden=true;$('#appPanel').hidden=false;$('#logoutBtn').hidden=false;$('#adminIdentity').textContent=r.email;renderList()}catch{logout()}}})();
})();
