export default {
  "id": "publication-38",
  "type": "research",
  "order": 38,
  "dateLabelEn": "Date not specified",
  "dateLabelBn": "তারিখ উল্লেখ\nনেই",
  "language": "Bengali",
  "titleEn": "বস্ত্র ও বাসস্থান",
  "titleBn": "বস্ত্র ও বাসস্থান",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Hadith O Samajik Biggan",
  "sourceBn": "হাদীস ও সামাজিক বিজ্ঞান",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
