export default {
  "id": "publication-49",
  "type": "edited",
  "order": 49,
  "dateLabelEn": "",
  "dateLabelBn": "",
  "language": "Bengali",
  "titleEn": "ইসলামী আইনের উৎস",
  "titleBn": "ইসলামী আইনের উৎস",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "",
  "sourceBn": "",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Muhammad Ruhul Amin, Bangladesh Islamic Law Research & Legal Aid Centre, 2013",
  "detailsBn": "মুহাম্মাদ রুহুল আমীন, বাংলাদেশ ইসলামিক ল’ রিসার্চ অ্যান্ড লিগ্যাল এইড সেন্টার, ২০১৩",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
