export default {
  "id": "publication-51",
  "type": "translation",
  "order": 51,
  "dateLabelEn": "",
  "dateLabelBn": "",
  "language": "Bengali",
  "titleEn": "আরবী-বাংলা অভিধান",
  "titleBn": "আরবী-বাংলা অভিধান",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "",
  "sourceBn": "",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "selected portions; Islamic Foundation Bangladesh, Dhaka",
  "detailsBn": "নির্বাচিত অংশ; ইসলামিক ফাউন্ডেশন বাংলাদেশ, ঢাকা",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
