export default {
  "id": "publication-33",
  "type": "research",
  "order": 33,
  "dateLabelEn": "Jun\n1998",
  "dateLabelBn": "জুন\n১৯৯৮",
  "language": "Bengali",
  "titleEn": "হাদীস ইসলামী শরী‘আতের একটি প্রমাণ দলীল: একটি পর্যালোচনা",
  "titleBn": "হাদীস ইসলামী শরী‘আতের একটি প্রমাণ দলীল: একটি পর্যালোচনা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "The Chittagong University Journal of Arts",
  "sourceBn": "চট্টগ্রাম বিশ্ববিদ্যালয় জার্নাল অব আর্টস",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 14 · Publisher: University of Chittagong.",
  "detailsBn": "খণ্ড ১৪ · প্রকাশক: চট্টগ্রাম বিশ্ববিদ্যালয়.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
