export default {
  "id": "publication-35",
  "type": "research",
  "order": 35,
  "dateLabelEn": "Jul–Sep\n1997",
  "dateLabelBn": "জুলাই–সেপ্টেম্বর\n১৯৯৭",
  "language": "Bengali",
  "titleEn": "ফার্সী লিপিকলা : উৎপত্তি ও বিকাশ",
  "titleBn": "ফার্সী লিপিকলা : উৎপত্তি ও বিকাশ",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Islamic Foundation Bangladesh Patrika",
  "sourceBn": "ইফা পত্রিকা",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 37, Issue 1 · Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "বর্ষ ৩৭, সংখ্যা ১ · প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
