export default {
  "id": "publication-30",
  "type": "research",
  "order": 30,
  "dateLabelEn": "Feb\n1999",
  "dateLabelBn": "ফেব্রুয়ারি\n১৯৯৯",
  "language": "Bengali",
  "titleEn": "আধুনিক আরবী কাব্যের জড় অধ্যায়: একটি পর্যালোচনা",
  "titleBn": "আধুনিক আরবী কাব্যের জড় অধ্যায়: একটি পর্যালোচনা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Agrapathik",
  "sourceBn": "অগ্রপথিক",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 14, Issue 2 · Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "বর্ষ ১৪, সংখ্যা ২ · প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
