export default {
  "id": "publication-47",
  "type": "edited",
  "order": 47,
  "dateLabelEn": "",
  "dateLabelBn": "",
  "language": "Bengali",
  "titleEn": "ইসলামী আইন ও বিচার",
  "titleBn": "ইসলামী আইন ও বিচার",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "",
  "sourceBn": "",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "quarterly research journal (from Oct–Dec 2013)",
  "detailsBn": "ত্রৈমাসিক গবেষণা পত্রিকা (অক্টোবর–ডিসেম্বর ২০১৩ থেকে)",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
