export default {
  "id": "publication-32",
  "type": "research",
  "order": 32,
  "dateLabelEn": "Jun\n1998",
  "dateLabelBn": "জুন\n১৯৯৮",
  "language": "Bengali",
  "titleEn": "আধুনিক আরবী সাহিত্যে পাশ্চাত্য সাহিত্যের প্রভাব",
  "titleBn": "আধুনিক আরবী সাহিত্যে পাশ্চাত্য সাহিত্যের প্রভাব",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Agrapathik",
  "sourceBn": "অগ্রপথিক",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 13, Issue 6 · Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "বর্ষ ১৩, সংখ্যা ৬ · প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
