export default {
  "id": "publication-31",
  "type": "research",
  "order": 31,
  "dateLabelEn": "Jul\n1998",
  "dateLabelBn": "জুলাই\n১৯৯৮",
  "language": "Bengali",
  "titleEn": "আরবী কবিতায় হযরত মহানবী (সা.)-এর প্রশস্তি",
  "titleBn": "আরবী কবিতায় হযরত মহানবী (সা.)-এর প্রশস্তি",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Sirat Smaranika",
  "sourceBn": "সীরাত স্মরণিকা",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "1419 AH · Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "১৪১৯ হি. · প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
