export default {
  "id": "publication-11",
  "type": "research",
  "order": 11,
  "dateLabelEn": "2005",
  "dateLabelBn": "২০০৫",
  "language": "Bengali",
  "titleEn": "ইসলামী সাহিত্য: প্রকৃতি ও পরিধি",
  "titleBn": "ইসলামী সাহিত্য: প্রকৃতি ও পরিধি",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Jumabar",
  "sourceBn": "জুমাবার",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 7, Al-Qur’an Issue.",
  "detailsBn": "বর্ষ ৭, আল-কুরআন সংখ্যা.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
