export default {
  "id": "publication-18",
  "type": "research",
  "order": 18,
  "dateLabelEn": "Jun\n2001",
  "dateLabelBn": "জুন\n২০০১",
  "language": "Bengali",
  "titleEn": "বাংলায় বিভিন্ন আরবী লিখন শৈলীর ব্যবহার: একটি সমীক্ষা",
  "titleBn": "বাংলায় বিভিন্ন আরবী লিখন শৈলীর ব্যবহার: একটি সমীক্ষা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Bangladesh Asiatic Society Patrika",
  "sourceBn": "বাংলাদেশ এশিয়াটিক সোসাইটি পত্রিকা",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 19, No. 1 · Publisher: The Asiatic Society of Bangladesh.",
  "detailsBn": "খণ্ড ১৯, সংখ্যা ১ · প্রকাশক: বাংলাদেশ এশিয়াটিক সোসাইটি.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
