export default {
  "id": "publication-21",
  "type": "research",
  "order": 21,
  "dateLabelEn": "2001",
  "dateLabelBn": "২০০১",
  "language": "Bengali",
  "titleEn": "ইসলামের দৃষ্টিতে পোশাক",
  "titleBn": "ইসলামের দৃষ্টিতে পোশাক",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "At-Takbir",
  "sourceBn": "আত-তাকবীর",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Issue 7 · Publisher: University of Chittagong Jame Masjid.",
  "detailsBn": "সংখ্যা ৭ · প্রকাশক: চট্টগ্রাম বিশ্ববিদ্যালয় জামে মসজিদ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
