export default {
  "id": "publication-23",
  "type": "research",
  "order": 23,
  "dateLabelEn": "Jun\n2000",
  "dateLabelBn": "জুন\n২০০০",
  "language": "Bengali",
  "titleEn": "হুযূর (সা.) ও সাহাবীদের আমলে হাদীস লিখন: একটি পর্যালোচনা",
  "titleBn": "হুযূর (সা.) ও সাহাবীদের আমলে হাদীস লিখন: একটি পর্যালোচনা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Agrapathik",
  "sourceBn": "অগ্রপথিক",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 15, Issue 6 · Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "বর্ষ ১৫, সংখ্যা ৬ · প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
