export default {
  "id": "publication-6",
  "type": "research",
  "order": 6,
  "dateLabelEn": "Jul–Sep\n2014",
  "dateLabelBn": "জুলাই–সেপ্টেম্বর\n২০১৪",
  "language": "Bengali",
  "titleEn": "Access to Housing: An Islamic Perspective",
  "titleBn": "আবাসগৃহে প্রবেশাধিকার : ইসলামী দৃষ্টিকোণ",
  "titleAr": "",
  "originalTitleBn": "আবাসগৃহে প্রবেশাধিকার : ইসলামী দৃষ্টিকোণ",
  "sourceEn": "Islami Ain O Bichar",
  "sourceBn": "ইসলামী আইন ও বিচার",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Issue 39 · Issue date: Jul–Sep 2014 · Publisher: Bangladesh Islamic Law Research & Legal Aid Centre · Verified in the journal’s published-article index.",
  "detailsBn": "সংখ্যা ৩৯ · সংখ্যা প্রকাশকাল: জুলাই–সেপ্টেম্বর ২০১৪ · প্রকাশক: বাংলাদেশ ইসলামিক ল’ রিসার্চ অ্যান্ড লিগ্যাল এইড সেন্টার · জার্নালের প্রকাশিত প্রবন্ধের সূচিতে যাচাইকৃত.",
  "articleUrl": "https://ilrcbd.org/en/list-of-published-article/",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
