export default {
  "id": "publication-13",
  "type": "research",
  "order": 13,
  "dateLabelEn": "Jun\n2002",
  "dateLabelBn": "জুন\n২০০২",
  "language": "Bengali",
  "titleEn": "ইসলামে বাসস্থান : অধিকার ও নিরাপত্তা",
  "titleBn": "ইসলামে বাসস্থান : অধিকার ও নিরাপত্তা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "The Chittagong University Journal of Arts",
  "sourceBn": "চট্টগ্রাম বিশ্ববিদ্যালয় জার্নাল অব আর্টস",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 18 · Publisher: University of Chittagong.",
  "detailsBn": "খণ্ড ১৮ · প্রকাশক: চট্টগ্রাম বিশ্ববিদ্যালয়.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
