export default {
  "id": "publication-29",
  "type": "research",
  "order": 29,
  "dateLabelEn": "Jun\n1999",
  "dateLabelBn": "জুন\n১৯৯৯",
  "language": "Bengali",
  "titleEn": "সমাজের সুখ ও শান্তি প্রতিষ্ঠায় হযরত মহানবী (সা.)",
  "titleBn": "সমাজের সুখ ও শান্তি প্রতিষ্ঠায় হযরত মহানবী (সা.)",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Agrapathik",
  "sourceBn": "অগ্রপথিক",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 14, Issue 6 · Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "বর্ষ ১৪, সংখ্যা ৬ · প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
