export default {
  "id": "publication-34",
  "type": "research",
  "order": 34,
  "dateLabelEn": "Jun\n1998",
  "dateLabelBn": "জুন\n১৯৯৮",
  "language": "Bengali",
  "titleEn": "তুঘরা লিপিশৈলী : উৎপত্তি ও বিকাশ",
  "titleBn": "তুঘরা লিপিশৈলী : উৎপত্তি ও বিকাশ",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Bangladesh Asiatic Society Patrika",
  "sourceBn": "বাংলাদেশ এশিয়াটিক সোসাইটি পত্রিকা",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 16, No. 1 · Publisher: The Asiatic Society of Bangladesh.",
  "detailsBn": "খণ্ড ১৬, সংখ্যা ১ · প্রকাশক: বাংলাদেশ এশিয়াটিক সোসাইটি.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
