export default {
  "id": "publication-16",
  "type": "research",
  "order": 16,
  "dateLabelEn": "Jun\n2001",
  "dateLabelBn": "জুন\n২০০১",
  "language": "Bengali",
  "titleEn": "মৌলিক অধিকার প্রতিষ্ঠায় হযরত মুহাম্মদ (সা.)",
  "titleBn": "মৌলিক অধিকার প্রতিষ্ঠায় হযরত মুহাম্মদ (সা.)",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Agrapathik",
  "sourceBn": "অগ্রপথিক",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 16, Issue 6 · Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "বর্ষ ১৬, সংখ্যা ৬ · প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
