export default {
  "id": "publication-28",
  "type": "research",
  "order": 28,
  "dateLabelEn": "Jun\n1999",
  "dateLabelBn": "জুন\n১৯৯৯",
  "language": "Bengali",
  "titleEn": "প্রবাসী আরব কবিদের নিমগ্ন বৈদগ্ধ্য",
  "titleBn": "প্রবাসী আরব কবিদের নিমগ্ন বৈদগ্ধ্য",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "The Chittagong University Journal of Arts",
  "sourceBn": "চট্টগ্রাম বিশ্ববিদ্যালয় জার্নাল অব আর্টস",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 15 · Publisher: University of Chittagong.",
  "detailsBn": "খণ্ড ১৫ · প্রকাশক: চট্টগ্রাম বিশ্ববিদ্যালয়.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
