export default {
  "id": "publication-1",
  "type": "research",
  "order": 1,
  "dateLabelEn": "Jan–Mar\n2026",
  "dateLabelBn": "জানুয়ারি–মার্চ\n২০২৬",
  "language": "Bengali",
  "titleEn": "The Islamization of Existing Laws in Bangladesh: Challenges and Pathways to Transformation",
  "titleBn": "বাংলাদেশের বিদ্যমান আইন ইসলামিকরণ : সমস্যা ও উত্তরণের উপায়",
  "titleAr": "",
  "originalTitleBn": "বাংলাদেশের বিদ্যমান আইন ইসলামিকরণ : সমস্যা ও উত্তরণের উপায়",
  "sourceEn": "Islami Ain O Bichar",
  "sourceBn": "ইসলামী আইন ও বিচার",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 22, No. 85, pp. 9–52 · Issue: Jan–Mar 2026 · OJS online publication: May 10, 2026 · Publisher: Bangladesh Islamic Law Research & Legal Aid Centre.",
  "detailsBn": "খণ্ড ২২, সংখ্যা ৮৫, পৃ. ৯–৫২ · সংখ্যা প্রকাশকাল: জানুয়ারি–মার্চ ২০২৬ · OJS অনলাইন প্রকাশ: ১০ মে ২০২৬ · প্রকাশক: বাংলাদেশ ইসলামিক ল’ রিসার্চ অ্যান্ড লিগ্যাল এইড সেন্টার.",
  "articleUrl": "https://www.islamiainobichar.com/index.php/iab/article/view/347",
  "doi": "https://doi.org/10.58666/iab.v22i85.347",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
