export default {
  "id": "publication-19",
  "type": "research",
  "order": 19,
  "dateLabelEn": "May\n2001",
  "dateLabelBn": "মে\n২০০১",
  "language": "Bengali",
  "titleEn": "মিসরের জাতীয় জাগরণের কবি হাফিয ইব্রাহীম : জীবন ও সাহিত্য সাধনা",
  "titleBn": "মিসরের জাতীয় জাগরণের কবি হাফিয ইব্রাহীম : জীবন ও সাহিত্য সাধনা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Agrapathik",
  "sourceBn": "অগ্রপথিক",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 16, Issue 5 · Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "বর্ষ ১৬, সংখ্যা ৫ · প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
