export default {
  "id": "publication-24",
  "type": "research",
  "order": 24,
  "dateLabelEn": "Jun\n2000",
  "dateLabelBn": "জুন\n২০০০",
  "language": "Bengali",
  "titleEn": "ইসলামী জনকল্যাণমূলক রাষ্ট্রে শূরা ব্যবস্থা : কাঠামো ও কার্যকারিতা",
  "titleBn": "ইসলামী জনকল্যাণমূলক রাষ্ট্রে শূরা ব্যবস্থা : কাঠামো ও কার্যকারিতা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "The Chittagong University Journal of Arts",
  "sourceBn": "চট্টগ্রাম বিশ্ববিদ্যালয় জার্নাল অব আর্টস",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 16 · Publisher: University of Chittagong.",
  "detailsBn": "খণ্ড ১৬ · প্রকাশক: চট্টগ্রাম বিশ্ববিদ্যালয়.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
