export default {
  "id": "publication-37",
  "type": "research",
  "order": 37,
  "dateLabelEn": "Date not specified",
  "dateLabelBn": "তারিখ উল্লেখ\nনেই",
  "language": "Bengali",
  "titleEn": "গাযওয়া বনী লিহয়ান",
  "titleBn": "গাযওয়া বনী লিহয়ান",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Sirat Encyclopedia",
  "sourceBn": "সীরাত বিশ্বকোষ",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
