export default {
  "id": "publication-45",
  "type": "arabic",
  "order": 45,
  "dateLabelEn": "1419\nAH",
  "dateLabelBn": "১৪১৯\nহি.",
  "language": "Arabic",
  "titleEn": "",
  "titleBn": "",
  "titleAr": "أبو الأسود الدؤلي ودوره في وضع قواعد النحو",
  "originalTitleBn": "",
  "sourceEn": "البعث الإسلامي، ندوة العلماء، لكنهو، الهند",
  "sourceBn": "البعث الإسلامي، ندوة العلماء، لكنهو، الهند",
  "sourceAr": "البعث الإسلامي، ندوة العلماء، لكنهو، الهند",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 44 · Publisher: Nadwatul Ulama, Lucknow, India.",
  "detailsBn": "খণ্ড ৪৪ · প্রকাশক: নদওয়াতুল উলামা, লক্ষ্ণৌ, ভারত.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
