export default {
  "id": "publication-5",
  "type": "research",
  "order": 5,
  "dateLabelEn": "Apr–Jun\n2016",
  "dateLabelBn": "এপ্রিল–জুন\n২০১৬",
  "language": "Bengali",
  "titleEn": "Juristic Disagreement: Nature & Manners",
  "titleBn": "ফিক্হী ইখতিলাফ (মতপার্থক্য) : স্বরূপ ও শিষ্টাচার",
  "titleAr": "",
  "originalTitleBn": "ফিক্হী ইখতিলাফ (মতপার্থক্য) : স্বরূপ ও শিষ্টাচার",
  "sourceEn": "Islami Ain O Bichar",
  "sourceBn": "ইসলামী আইন ও বিচার",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 12, No. 46, pp. 37–71 · Issue: Apr–Jun 2016 · OJS online archive publication: Oct 18, 2023 · Publisher: Bangladesh Islamic Law Research & Legal Aid Centre.",
  "detailsBn": "খণ্ড ১২, সংখ্যা ৪৬, পৃ. ৩৭–৭১ · সংখ্যা প্রকাশকাল: এপ্রিল–জুন ২০১৬ · OJS অনলাইন আর্কাইভ প্রকাশ: ১৮ অক্টোবর ২০২৩ · প্রকাশক: বাংলাদেশ ইসলামিক ল’ রিসার্চ অ্যান্ড লিগ্যাল এইড সেন্টার.",
  "articleUrl": "https://islamiainobichar.com/index.php/iab/article/view/18",
  "doi": "https://doi.org/10.58666/ysh2fq77",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
