export default {
  "id": "publication-2",
  "type": "research",
  "order": 2,
  "dateLabelEn": "Apr–Sep\n2023",
  "dateLabelBn": "এপ্রিল–সেপ্টেম্বর\n২০২৩",
  "language": "Bengali",
  "titleEn": "Enjoyment of Cash-Waqif the Profit and Encashment of Principal Amount: A Comparative Fiqh Analysis",
  "titleBn": "ক্যাশ ওয়াক্ফকারীর লভ্যাংশ ভোগ ও মূল টাকা উত্তোলন : একটি ফিকহী বিশ্লেষণ",
  "titleAr": "",
  "originalTitleBn": "ক্যাশ ওয়াক্ফকারীর লভ্যাংশ ভোগ ও মূল টাকা উত্তোলন : একটি ফিকহী বিশ্লেষণ",
  "sourceEn": "Islami Ain O Bichar",
  "sourceBn": "ইসলামী আইন ও বিচার",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 19, Nos. 74–75, pp. 9–30 · Issue: Apr–Sep 2023 · OJS online publication: Sep 9, 2023 · Publisher: Bangladesh Islamic Law Research & Legal Aid Centre.",
  "detailsBn": "খণ্ড ১৯, সংখ্যা ৭৪–৭৫, পৃ. ৯–৩০ · সংখ্যা প্রকাশকাল: এপ্রিল–সেপ্টেম্বর ২০২৩ · OJS অনলাইন প্রকাশ: ৯ সেপ্টেম্বর ২০২৩ · প্রকাশক: বাংলাদেশ ইসলামিক ল’ রিসার্চ অ্যান্ড লিগ্যাল এইড সেন্টার.",
  "articleUrl": "https://www.islamiainobichar.com/index.php/iab/article/view/255",
  "doi": "https://doi.org/10.58666/iab.v19i74-75.255",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
