export default {
  "id": "publication-15",
  "type": "research",
  "order": 15,
  "dateLabelEn": "Jul–Sep\n2001",
  "dateLabelBn": "জুলাই–সেপ্টেম্বর\n২০০১",
  "language": "Bengali",
  "titleEn": "রাসূলুল্লাহ (সা.)-এর পরামর্শ ব্যবস্থা",
  "titleBn": "রাসূলুল্লাহ (সা.)-এর পরামর্শ ব্যবস্থা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Islamic Foundation Bangladesh Patrika",
  "sourceBn": "ই.ফা.বা পত্রিকা",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 41, Issue 1 · Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "বর্ষ ৪১, সংখ্যা ১ · প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
