export default {
  "id": "publication-43",
  "type": "arabic",
  "order": 43,
  "dateLabelEn": "1421\nAH",
  "dateLabelBn": "১৪২১\nহি.",
  "language": "Arabic",
  "titleEn": "",
  "titleBn": "",
  "titleAr": "السيدة عائشة رضي الله تعالى عنها: القدوة المثلى في العلم والأدب",
  "originalTitleBn": "",
  "sourceEn": "البعث الإسلامي، ندوة العلماء، لكنهو، الهند",
  "sourceBn": "البعث الإسلامي، ندوة العلماء، لكنهو، الهند",
  "sourceAr": "البعث الإسلامي، ندوة العلماء، لكنهو، الهند",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 46 · Publisher: Nadwatul Ulama, Lucknow, India.",
  "detailsBn": "খণ্ড ৪৬ · প্রকাশক: নদওয়াতুল উলামা, লক্ষ্ণৌ, ভারত.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
