export default {
  "id": "publication-27",
  "type": "research",
  "order": 27,
  "dateLabelEn": "2000",
  "dateLabelBn": "২০০০",
  "language": "Bengali",
  "titleEn": "রাসূলুল্লাহ (সা.)-এর শূরা ব্যবস্থা ও গণতন্ত্র",
  "titleBn": "রাসূলুল্লাহ (সা.)-এর শূরা ব্যবস্থা ও গণতন্ত্র",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "At-Takbir",
  "sourceBn": "আত-তাকবীর",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Issue 6 · Publisher: University of Chittagong Jame Masjid.",
  "detailsBn": "সংখ্যা ৬ · প্রকাশক: চট্টগ্রাম বিশ্ববিদ্যালয় জামে মসজিদ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
