export default {
  "id": "publication-20",
  "type": "research",
  "order": 20,
  "dateLabelEn": "Mar\n2001",
  "dateLabelBn": "মার্চ\n২০০১",
  "language": "Bengali",
  "titleEn": "কুরবানী রসম নয়; একটি জীবন্ত সত্য",
  "titleBn": "কুরবানী রসম নয়; একটি জীবন্ত সত্য",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Agrapathik",
  "sourceBn": "অগ্রপথিক",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 16, Issue 3 · Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "বর্ষ ১৬, সংখ্যা ৩ · প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
