export default {
  "id": "publication-10",
  "type": "research",
  "order": 10,
  "dateLabelEn": "Jun\n2005",
  "dateLabelBn": "জুন\n২০০৫",
  "language": "Bengali",
  "titleEn": "আরবী লিখন শিল্পের উৎপত্তি সম্পর্কে বিভিন্ন মত: একটি পর্যালোচনা",
  "titleBn": "আরবী লিখন শিল্পের উৎপত্তি সম্পর্কে বিভিন্ন মত: একটি পর্যালোচনা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Itihas Patrika (The Journal of History)",
  "sourceBn": "ইতিহাস পত্রিকা",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Issue 6 · Publisher: University of Chittagong.",
  "detailsBn": "সংখ্যা ৬ · প্রকাশক: চট্টগ্রাম বিশ্ববিদ্যালয়.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
