export default {
  "id": "publication-48",
  "type": "edited",
  "order": 48,
  "dateLabelEn": "",
  "dateLabelBn": "",
  "language": "Bengali",
  "titleEn": "ইসলামে অমুসলিমদের অধিকার",
  "titleBn": "ইসলামে অমুসলিমদের অধিকার",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "",
  "sourceBn": "",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Muhammad Sharif Uddin Chowdhury, Bangladesh Islamic Law Research & Legal Aid Centre, 2015",
  "detailsBn": "মুহাম্মদ শরীফ উদ্দীন চৌধুরী, বাংলাদেশ ইসলামিক ল’ রিসার্চ অ্যান্ড লিগ্যাল এইড সেন্টার, ২০১৫",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
