export default {
  "id": "publication-42",
  "type": "arabic",
  "order": 42,
  "dateLabelEn": "1998–1999",
  "dateLabelBn": "১৯৯৮–১৯৯৯",
  "language": "Arabic",
  "titleEn": "",
  "titleBn": "",
  "titleAr": "الزجاج ودوره في علم النحو",
  "originalTitleBn": "",
  "sourceEn": "المجلة العربية، جامعة داكا",
  "sourceBn": "المجلة العربية، جامعة داكا",
  "sourceAr": "المجلة العربية، جامعة داكا",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 4, Issues 4–5 · Publisher: University of Dhaka.",
  "detailsBn": "খণ্ড ৪, সংখ্যা ৪–৫ · প্রকাশক: ঢাকা বিশ্ববিদ্যালয়.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
