export default {
  "id": "publication-4",
  "type": "research",
  "order": 4,
  "dateLabelEn": "Jul–Dec\n2017",
  "dateLabelBn": "জুলাই–ডিসেম্বর\n২০১৭",
  "language": "Bengali",
  "titleEn": "Prioritization Policy in Islamic Law: An Analysis",
  "titleBn": "ইসলামী বিধানে অগ্রাধিকার নির্ধারণ নীতি: একটি পর্যালোচনা",
  "titleAr": "",
  "originalTitleBn": "ইসলামী বিধানে অগ্রাধিকার নির্ধারণ নীতি: একটি পর্যালোচনা",
  "sourceEn": "Islami Ain O Bichar",
  "sourceBn": "ইসলামী আইন ও বিচার",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 13, Nos. 51–52, pp. 9–50 · Issue: Jul–Dec 2017 · OJS online archive publication: Oct 17, 2023 · Publisher: Bangladesh Islamic Law Research & Legal Aid Centre.",
  "detailsBn": "খণ্ড ১৩, সংখ্যা ৫১–৫২, পৃ. ৯–৫০ · সংখ্যা প্রকাশকাল: জুলাই–ডিসেম্বর ২০১৭ · OJS অনলাইন আর্কাইভ প্রকাশ: ১৭ অক্টোবর ২০২৩ · প্রকাশক: বাংলাদেশ ইসলামিক ল’ রিসার্চ অ্যান্ড লিগ্যাল এইড সেন্টার.",
  "articleUrl": "https://islamiainobichar.com/index.php/iab/article/view/95",
  "doi": "",
  "pdfUrl": "https://islamiainobichar.com/index.php/iab/article/download/95/80/231",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
