export default {
  "id": "publication-36",
  "type": "research",
  "order": 36,
  "dateLabelEn": "Jun\n1997",
  "dateLabelBn": "জুন\n১৯৯৭",
  "language": "Bengali",
  "titleEn": "আল-কুর’আন শব্দের মূল ও এর পবিত্র নামসমূহ: একটি আভিধানিক বিশ্লেষণ",
  "titleBn": "আল-কুর’আন শব্দের মূল ও এর পবিত্র নামসমূহ: একটি আভিধানিক বিশ্লেষণ",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "The Chittagong University Journal of Arts",
  "sourceBn": "চট্টগ্রাম বিশ্ববিদ্যালয় জার্নাল অব আর্টস",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 13 · Publisher: University of Chittagong.",
  "detailsBn": "খণ্ড ১৩ · প্রকাশক: চট্টগ্রাম বিশ্ববিদ্যালয়.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
