export default {
  "id": "publication-44",
  "type": "arabic",
  "order": 44,
  "dateLabelEn": "1420\nAH",
  "dateLabelBn": "১৪২০\nহি.",
  "language": "Arabic",
  "titleEn": "",
  "titleBn": "",
  "titleAr": "هل يصح تقسيم البدعة إلى حسنة وسيئة؟",
  "originalTitleBn": "",
  "sourceEn": "البعث الإسلامي، ندوة العلماء، لكنهو، الهند",
  "sourceBn": "البعث الإسلامي، ندوة العلماء، لكنهو، الهند",
  "sourceAr": "البعث الإسلامي، ندوة العلماء، لكنهو، الهند",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 45 · Publisher: Nadwatul Ulama, Lucknow, India.",
  "detailsBn": "খণ্ড ৪৫ · প্রকাশক: নদওয়াতুল উলামা, লক্ষ্ণৌ, ভারত.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
