export default {
  "id": "publication-9",
  "type": "research",
  "order": 9,
  "dateLabelEn": "Mar\n2008",
  "dateLabelBn": "মার্চ\n২০০৮",
  "language": "Bengali",
  "titleEn": "ইসলামী শিক্ষা বিস্তারে বাংলা ভাষা শিক্ষার গুরুত্ব",
  "titleBn": "ইসলামী শিক্ষা বিস্তারে বাংলা ভাষা শিক্ষার গুরুত্ব",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Jumabar",
  "sourceBn": "জুমাবার",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 9.",
  "detailsBn": "বর্ষ ৯.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
