export default {
  "id": "publication-8",
  "type": "research",
  "order": 8,
  "dateLabelEn": "Aug\n2008",
  "dateLabelBn": "আগস্ট\n২০০৮",
  "language": "Bengali",
  "titleEn": "ইসলাম ও গণতন্ত্র",
  "titleBn": "ইসলাম ও গণতন্ত্র",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Mehrab",
  "sourceBn": "মেহরাব",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Issue 5 · Publisher: BPRF.",
  "detailsBn": "সংখ্যা ৫ · প্রকাশক: বিপিআরএফ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
