export default {
  "id": "publication-14",
  "type": "research",
  "order": 14,
  "dateLabelEn": "2002",
  "dateLabelBn": "২০০২",
  "language": "Bengali",
  "titleEn": "রাসূলুল্লাহ (সা.)-এর সাহিত্য-চিন্তা: স্বরূপ ও প্রভাব",
  "titleBn": "রাসূলুল্লাহ (সা.)-এর সাহিত্য-চিন্তা: স্বরূপ ও প্রভাব",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "At-Takbir",
  "sourceBn": "আত-তাকবীর",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Issue 8 · Publisher: University of Chittagong Jame Masjid.",
  "detailsBn": "সংখ্যা ৮ · প্রকাশক: চট্টগ্রাম বিশ্ববিদ্যালয় জামে মসজিদ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
