export default {
  "id": "publication-12",
  "type": "research",
  "order": 12,
  "dateLabelEn": "Nov\n2003",
  "dateLabelBn": "নভেম্বর\n২০০৩",
  "language": "Bengali",
  "titleEn": "হযরত আবূ বকর সিদ্দীক (রা.)-এর শাসন ব্যবস্থা: একটি পর্যালোচনা",
  "titleBn": "হযরত আবূ বকর সিদ্দীক (রা.)-এর শাসন ব্যবস্থা: একটি পর্যালোচনা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "The Chittagong University Journal of Arts",
  "sourceBn": "চট্টগ্রাম বিশ্ববিদ্যালয় জার্নাল অব আর্টস",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 19 · Publisher: University of Chittagong.",
  "detailsBn": "খণ্ড ১৯ · প্রকাশক: চট্টগ্রাম বিশ্ববিদ্যালয়.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
