export default {
  "id": "publication-7",
  "type": "research",
  "order": 7,
  "dateLabelEn": "2010",
  "dateLabelBn": "২০১০",
  "language": "Bengali",
  "titleEn": "রাসূলুল্লাহ (সা.)-এর মাদীনা মুনাওয়ারা",
  "titleBn": "রাসূলুল্লাহ (সা.)-এর মাদীনা মুনাওয়ারা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Prekkhon (Literary Quarterly), Hajj Issue",
  "sourceBn": "প্রেক্ষণ (সাহিত্য ত্রৈমাসিক), হজ্জ সংখ্যা",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": ".",
  "detailsBn": ".",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
