export default {
  "id": "publication-46",
  "type": "arabic",
  "order": 46,
  "dateLabelEn": "1997",
  "dateLabelBn": "১৯৯৭",
  "language": "Arabic",
  "titleEn": "",
  "titleBn": "",
  "titleAr": "نفطويه النحوي: حياته وآثاره",
  "originalTitleBn": "",
  "sourceEn": "المجلة العربية، جامعة داكا",
  "sourceBn": "المجلة العربية، جامعة داكا",
  "sourceAr": "المجلة العربية، جامعة داكا",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 3, Issue 3 · Publisher: University of Dhaka.",
  "detailsBn": "খণ্ড ৩, সংখ্যা ৩ · প্রকাশক: ঢাকা বিশ্ববিদ্যালয়.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
