export default {
  "id": "publication-39",
  "type": "arabic",
  "order": 39,
  "dateLabelEn": "2013 / 1434 AH",
  "dateLabelBn": "২০১৩ / ১৪৩৪ হি.",
  "language": "Arabic",
  "titleEn": "",
  "titleBn": "",
  "titleAr": "الآثار التعبدية والروحية لفقه الأوليات في الحج",
  "originalTitleBn": "",
  "sourceEn": "مجلة ندوة الحج الكبرى",
  "sourceBn": "مجلة ندوة الحج الكبرى",
  "sourceAr": "مجلة ندوة الحج الكبرى",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Grand Hajj Symposium · Publisher: Ministry of Hajj, Makkah, Saudi Arabia.",
  "detailsBn": "গ্র্যান্ড হজ সিম্পোজিয়াম · প্রকাশক: হজ মন্ত্রণালয়, মক্কা, সৌদি আরব.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
