export default {
  "id": "publication-17",
  "type": "research",
  "order": 17,
  "dateLabelEn": "Jun\n2001",
  "dateLabelBn": "জুন\n২০০১",
  "language": "Bengali",
  "titleEn": "লিখন শিল্পের গোড়ার কথা",
  "titleBn": "লিখন শিল্পের গোড়ার কথা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "The Chittagong University Journal of Arts",
  "sourceBn": "চট্টগ্রাম বিশ্ববিদ্যালয় জার্নাল অব আর্টস",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Vol. 17 · Publisher: University of Chittagong.",
  "detailsBn": "খণ্ড ১৭ · প্রকাশক: চট্টগ্রাম বিশ্ববিদ্যালয়.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
