export default {
  "id": "publication-25",
  "type": "research",
  "order": 25,
  "dateLabelEn": "May\n2000",
  "dateLabelBn": "মে\n২০০০",
  "language": "Bengali",
  "titleEn": "আধুনিকতা-পূর্ব আরবী কবিতা",
  "titleBn": "আধুনিকতা-পূর্ব আরবী কবিতা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Agrapathik",
  "sourceBn": "অগ্রপথিক",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 15, Issue 5 · Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "বর্ষ ১৫, সংখ্যা ৫ · প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
