export default {
  "id": "publication-3",
  "type": "research",
  "order": 3,
  "dateLabelEn": "Sep\n2019",
  "dateLabelBn": "সেপ্টেম্বর\n২০১৯",
  "language": "Bengali",
  "titleEn": "মসজিদে চেয়ারের ব্যবহার এবং চেয়ারে বসে নামায আদায়",
  "titleBn": "মসজিদে চেয়ারের ব্যবহার এবং চেয়ারে বসে নামায আদায়",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Masik Prithibi",
  "sourceBn": "মাসিক পৃথিবী",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 38, Issue 12 · Publisher: Bangladesh Islamic Centre.",
  "detailsBn": "বর্ষ ৩৮, সংখ্যা ১২ · প্রকাশক: বাংলাদেশ ইসলামিক সেন্টার.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
