export default {
  "id": "publication-22",
  "type": "research",
  "order": 22,
  "dateLabelEn": "2001",
  "dateLabelBn": "২০০১",
  "language": "Bengali",
  "titleEn": "ইসমাতুল আম্বিয়া: একটি পর্যালোচনা",
  "titleBn": "ইসমাতুল আম্বিয়া: একটি পর্যালোচনা",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Islami Gabeshana Patrika",
  "sourceBn": "ইসলামী গবেষণা পত্রিকা",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Issue 2 · Publisher: University of Rajshahi.",
  "detailsBn": "সংখ্যা ২ · প্রকাশক: রাজশাহী বিশ্ববিদ্যালয়.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
