export default {
  "id": "publication-26",
  "type": "research",
  "order": 26,
  "dateLabelEn": "Apr–Jun\n2000",
  "dateLabelBn": "এপ্রিল–জুন\n২০০০",
  "language": "Bengali",
  "titleEn": "বিদ‘আতের পরিচয় ও প্রকারভেদ: একটি তাত্ত্বিক বিশ্লেষণ",
  "titleBn": "বিদ‘আতের পরিচয় ও প্রকারভেদ: একটি তাত্ত্বিক বিশ্লেষণ",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "Islamic Foundation Bangladesh Patrika",
  "sourceBn": "ইফাবা পত্রিকা",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 39, Issue 4 · Publisher: Islamic Foundation Bangladesh.",
  "detailsBn": "বর্ষ ৩৯, সংখ্যা ৪ · প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
