export default {
  "id": "publication-41",
  "type": "arabic",
  "order": 41,
  "dateLabelEn": "2003",
  "dateLabelBn": "২০০৩",
  "language": "Arabic",
  "titleEn": "",
  "titleBn": "",
  "titleAr": "الإعجام: نشأته و تطوره",
  "originalTitleBn": "",
  "sourceEn": "مجلة المؤسسة الإسلامية، داكا",
  "sourceBn": "مجلة المؤسسة الإسلامية، داكا",
  "sourceAr": "مجلة المؤسسة الإسلامية، داكا",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Year 42, Issue 4 · Publisher: Islamic Foundation Bangladesh, Dhaka.",
  "detailsBn": "বর্ষ ৪২, সংখ্যা ৪ · প্রকাশক: ইসলামিক ফাউন্ডেশন বাংলাদেশ, ঢাকা.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
