export default {
  "id": "publication-40",
  "type": "arabic",
  "order": 40,
  "dateLabelEn": "2005",
  "dateLabelBn": "২০০৫",
  "language": "Arabic",
  "titleEn": "",
  "titleBn": "",
  "titleAr": "مراحل اكتساب ونمو اللغة عند الطفل",
  "originalTitleBn": "",
  "sourceEn": "مجلة كلية الآداب، جامعة شيتاغونغ",
  "sourceBn": "مجلة كلية الآداب، جامعة شيتاغونغ",
  "sourceAr": "مجلة كلية الآداب، جامعة شيتاغونغ",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "Publisher: University of Chittagong.",
  "detailsBn": "প্রকাশক: চট্টগ্রাম বিশ্ববিদ্যালয়.",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
