export default {
  "id": "publication-50",
  "type": "translation",
  "order": 50,
  "dateLabelEn": "",
  "dateLabelBn": "",
  "language": "Bengali",
  "titleEn": "সাহীহুল বুখারী",
  "titleBn": "সাহীহুল বুখারী",
  "titleAr": "",
  "originalTitleBn": "",
  "sourceEn": "",
  "sourceBn": "",
  "sourceAr": "",
  "volume": "",
  "issue": "",
  "pages": "",
  "publisherEn": "",
  "publisherBn": "",
  "issueDateEn": "",
  "issueDateBn": "",
  "onlineDateEn": "",
  "onlineDateBn": "",
  "detailsEn": "selected portions; Bangladesh Islamic Centre, Dhaka",
  "detailsBn": "নির্বাচিত অংশ; বাংলাদেশ ইসলামিক সেন্টার, ঢাকা",
  "articleUrl": "",
  "doi": "",
  "pdfUrl": "",
  "otherUrl": "",
  "notesEn": "",
  "notesBn": ""
};
