const cors=(origin:string)=>({
  'Access-Control-Allow-Origin':origin||'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'
});
const json=(body:any,status=200,origin='*')=>new Response(JSON.stringify(body),{status,headers:cors(origin)});
const env=(k:string)=>Deno.env.get(k)||'';
const safeId=(v:any)=>{const s=String(v||'').trim();if(!/^[a-z0-9][a-z0-9-]{0,119}$/.test(s))throw new Error('Invalid id. Use lowercase letters, numbers and hyphens only.');return s};
const filePath=(type:string,id:string)=>({book:`books/${id}.mjs`,post:`posts/${id}.mjs`,article:`articles/${id}.mjs`,publication:`publications/${id}.mjs`,update:`updates/${id}.mjs`}[type]||'');
function utf8b64(s:string){const b=new TextEncoder().encode(s);let x='';for(let i=0;i<b.length;i+=32768)x+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(x)}
function ghHeaders(){return {'Authorization':`Bearer ${env('GITHUB_TOKEN')}`,'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'}}
function ghUrl(path:string){return `https://api.github.com/repos/${env('GITHUB_OWNER')}/${env('GITHUB_REPO')}/contents/${path.split('/').map(encodeURIComponent).join('/')}?ref=${encodeURIComponent(env('GITHUB_BRANCH')||'main')}`}
async function getFile(path:string){const r=await fetch(ghUrl(path),{headers:ghHeaders()});if(r.status===404)return null;if(!r.ok)throw new Error(`GitHub read failed (${r.status})`);return await r.json()}
async function putFile(path:string,content:string,message:string){const old=await getFile(path);const u=ghUrl(path).replace(/\?ref=.*$/,'');const body:any={message,content:utf8b64(content),branch:env('GITHUB_BRANCH')||'main'};if(old?.sha)body.sha=old.sha;const r=await fetch(u,{method:'PUT',headers:ghHeaders(),body:JSON.stringify(body)});if(!r.ok)throw new Error(`GitHub write failed (${r.status}): ${await r.text()}`);return await r.json()}
async function deleteFile(path:string,message:string){const old=await getFile(path);if(!old)return;const u=ghUrl(path).replace(/\?ref=.*$/,'');const r=await fetch(u,{method:'DELETE',headers:ghHeaders(),body:JSON.stringify({message,sha:old.sha,branch:env('GITHUB_BRANCH')||'main'})});if(!r.ok)throw new Error(`GitHub delete failed (${r.status})`)}
async function authUser(req:Request){const auth=req.headers.get('authorization')||'';if(!auth.startsWith('Bearer '))throw new Error('Not signed in.');const r=await fetch(`${env('SUPABASE_URL')}/auth/v1/user`,{headers:{apikey:env('SUPABASE_ANON_KEY'),Authorization:auth}});if(!r.ok)throw new Error('Session expired.');const user=await r.json();const q=await fetch(`${env('SUPABASE_URL')}/rest/v1/admin_users?user_id=eq.${encodeURIComponent(user.id)}&select=user_id,email`,{headers:{apikey:env('SUPABASE_SERVICE_ROLE_KEY'),Authorization:`Bearer ${env('SUPABASE_SERVICE_ROLE_KEY')}`}});const rows=await q.json();if(!Array.isArray(rows)||!rows.length)throw new Error('This account is not authorized as a website administrator.');return user}
Deno.serve(async(req)=>{const origin=req.headers.get('origin')||'*';if(req.method==='OPTIONS')return new Response('ok',{headers:cors(origin)});try{const user=await authUser(req);const p=await req.json();if(p.action==='whoami')return json({ok:true,email:user.email},200,origin);
if(p.action==='save'){const id=safeId(p.id),path=filePath(p.contentType,id);if(!path)throw new Error('Unknown content type.');const data={...(p.data||{}),id};const content=`export default ${JSON.stringify(data,null,2)};\n`;await putFile(path,content,`Admin: save ${p.contentType} ${id}`);return json({ok:true,path},200,origin)}
if(p.action==='delete'){const id=safeId(p.id),path=filePath(p.contentType,id);if(!path)throw new Error('Unknown content type.');await deleteFile(path,`Admin: delete ${p.contentType} ${id}`);return json({ok:true},200,origin)}
if(p.action==='upload'){const id=safeId(p.id);const ext=String(p.ext||'bin').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,8)||'bin';const kind=String(p.kind||'file').replace(/[^a-z0-9-]/gi,'').toLowerCase();if(!['cover','pdf','preview','audio'].includes(kind))throw new Error('Invalid asset kind.');const folder=p.contentType==='publication'?'publications':'books';const path=`media/${folder}/${id}/${kind}.${ext}`;const old=await getFile(path);const u=ghUrl(path).replace(/\?ref=.*$/,'');const body:any={message:`Admin: upload ${kind} for ${id}`,content:String(p.base64||''),branch:env('GITHUB_BRANCH')||'main'};if(old?.sha)body.sha=old.sha;const r=await fetch(u,{method:'PUT',headers:ghHeaders(),body:JSON.stringify(body)});if(!r.ok)throw new Error(`Asset upload failed (${r.status})`);return json({ok:true,path},200,origin)}
throw new Error('Unknown action.');}catch(e){return json({ok:false,error:String(e?.message||e)},400,origin)}});
